"""Initial v1 schema.

The complete v1 schema from BUILD_PLAN section 8.1: principals, registry_snapshots,
workflow_bindings, operations, operation_events, approvals, execution_results, and
audit_log. Generated by ``alembic revision --autogenerate`` against the ORM metadata in
``storage/models.py`` and reviewed unchanged — every constraint here (CHECK, UNIQUE,
FOREIGN KEY) traces to a rule documented in that module, and this file is exactly what
AC-24's "autogenerate produces an empty diff" check compares future schema states
against.

Revision ID: 0001
Revises: (none — the first migration)
Create Date: 2026-08-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("prev_hash", sa.String(), nullable=False),
        sa.Column("entry_hash", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('allowed', 'denied', 'error')", name="ck_audit_log_outcome"
        ),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("entry_hash"),
    )
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "principals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("external_subject", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('local', 'user', 'service')", name="ck_principals_kind"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "registry_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("environment", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("definition_hash", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("argument_fingerprint", sa.String(), nullable=False),
        sa.Column("argument_bytes", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("handle_burned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("n8n_execution_id", sa.String(), nullable=True),
        sa.Column("parent_operation_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('PREPARING', 'INVALID', 'BLOCKED', 'PENDING_APPROVAL', 'APPROVED', "
            "'REJECTED', 'EXPIRED', 'CANCELED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'UNKNOWN')",
            name="ck_operations_state",
        ),
        sa.ForeignKeyConstraint(
            ["parent_operation_id"],
            ["operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["registry_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "principal_id",
            "environment",
            "workflow_id",
            "idempotency_key",
            name="uq_operations_idempotency_namespace",
        ),
    )
    op.create_index(
        "ix_operations_parent_operation_id", "operations", ["parent_operation_id"], unique=False
    )
    op.create_index("ix_operations_principal_id", "operations", ["principal_id"], unique=False)
    op.create_index("ix_operations_snapshot_id", "operations", ["snapshot_id"], unique=False)
    op.create_index("ix_operations_state", "operations", ["state"], unique=False)
    op.create_index("ix_operations_workflow_id", "operations", ["workflow_id"], unique=False)
    op.create_table(
        "workflow_bindings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("n8n_workflow_id", sa.String(), nullable=False),
        sa.Column("definition_hash", sa.String(), nullable=False),
        sa.Column("side_effects", sa.String(), nullable=False),
        sa.Column("approval_policy", sa.String(), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "approval_policy IN ('none', 'required')", name="ck_workflow_bindings_approval_policy"
        ),
        sa.CheckConstraint(
            "side_effects IN ('read_only', 'external_write', 'irreversible')",
            name="ck_workflow_bindings_side_effects",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["registry_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "workflow_id", name="uq_workflow_bindings_snapshot_workflow"
        ),
    )
    op.create_index(
        "ix_workflow_bindings_snapshot_id", "workflow_bindings", ["snapshot_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("operation_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision", sa.String(), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.Column("client_fingerprint", sa.String(), nullable=True),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('approved', 'rejected')", name="ck_approvals_decision"
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_approvals_operation_id", "approvals", ["operation_id"], unique=False)
    op.create_table(
        "execution_results",
        sa.Column("operation_id", sa.String(), nullable=False),
        sa.Column("n8n_execution_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redacted_payload", sa.JSON(), nullable=False),
        sa.Column("node_trace", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "status IN ('success', 'error', 'indeterminate')", name="ck_execution_results_status"
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_table(
        "operation_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("operation_id", sa.String(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=True),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("transition", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "transition IN ('T01', 'T02', 'T03', 'T04', 'T05', 'T06', 'T07', 'T08', 'T09', "
            "'T10', 'T11', 'T12', 'T13', 'T14', 'T15')",
            name="ck_operation_events_transition",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_operation_events_operation_id", "operation_events", ["operation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_operation_events_operation_id", table_name="operation_events")
    op.drop_table("operation_events")
    op.drop_table("execution_results")
    op.drop_index("ix_approvals_operation_id", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_workflow_bindings_snapshot_id", table_name="workflow_bindings")
    op.drop_table("workflow_bindings")
    op.drop_index("ix_operations_workflow_id", table_name="operations")
    op.drop_index("ix_operations_state", table_name="operations")
    op.drop_index("ix_operations_snapshot_id", table_name="operations")
    op.drop_index("ix_operations_principal_id", table_name="operations")
    op.drop_index("ix_operations_parent_operation_id", table_name="operations")
    op.drop_table("operations")
    op.drop_table("registry_snapshots")
    op.drop_table("principals")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
