"""Approval binding hash.

Adds ``approvals.binding_hash`` (phase 6, ADR-010): a sha256 over the operation's own
``(id, principal_id, argument_fingerprint, snapshot_id, definition_hash)`` at mint time,
re-checked at redemption as defense in depth against a future regression that would let
an approval token be redeemed against a different operation than the one it was minted
for. Generated by ``alembic revision --autogenerate`` against the ORM metadata in
``storage/models.py`` and reviewed unchanged, exactly like 0001.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("approvals", sa.Column("binding_hash", sa.String(), nullable=False))


def downgrade() -> None:
    op.drop_column("approvals", "binding_hash")
